# Generated by Django 5.2.4 on 2025-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="post",
            name="equipment_used",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts_images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="location_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="observation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("observation", "Observation"),
                    ("astrophoto", "Astrophoto"),
                    ("question", "Question"),
                    ("discussion", "Discussion"),
                    ("guide", "Guide/Tutorial"),
                ],
                default="discussion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
